name: Formatting check
on: [push, pull_request]
jobs:
  lint_check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        make install
    - name: Format with black
      run: | 
        make format
    - name: Check linting
      run: |
        make lint
    - name: check using flake8
      run: |
        make flake