name: DSA-With-Python Workflow
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        make install
    - name: Format code with Python black
      run: |
        make format
    - name: Test with Pytest
      run: |
        make test
name: Docstring test
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -name: check code formating with flake 8
      run: |
        make flake
      - name: Lint with Pylint
        run: |
          make lint
    
